config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # Dashboard
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  # Authentication
  devise_for :users
 
  # Applications
  root to: 'home#index'
  resources :members, only: [:create]
  resources :about, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
# frozen_string_literal: true
class Member < ApplicationRecord
  self.table_name = 'members'
  self.primary_key = 'id'

  validates :name,
            presence: true,
            uniqueness: false,
            allow_blank: false,
            length: { minimum: 3, maximum: 40 }
 
  validates :email,
            presence: true,
            uniqueness: true,
            allow_blank: false,
            length: { minimum: 3, maximum: 245 }
end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  def index
  	@member = Member.new
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true
class MembersController < ApplicationController
	def create
		member = Member.find_or_create_by(member_params)
		redirect_to root_path, notice: "Membro registrado com sucesso."
	end

	private

	def member_params
		params.require(:member).permit(:name, :email)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<% provide :title, 'Sobre' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class='col-md-8 col-md-offset-2'>
			<h2 class='bold'>RUBY-SR</h2><br>
			<p>O <span class='bold'>RubySR</span>, Grupo de Usuários Ruby de São Roque, é uma associação de pessoas interessadas em aprender, ensinar e divulgar o uso da linguagem de programação Ruby e de seus diversos frameworks, bibliotecas e aplicações. O grupo também está aberto para a discussão de outros assuntos relacionados ao desenvolvimento de software, tais como: metodologias de desenvolvimento, novas tecnologias e mercado de trabalho.</p>
			<br>

			<p>O RubySR foi fundado em 26 de Abril de 2019 na lista de discussão. Iniciou-se com uma lista de discussão e tem como página oficial este site,cujo código fonte está disponível na conta do Github do grupo.</p>
			</div>
			<br>
			
			<div class='col-md-8 col-md-offset-2'>
			<h2 class='bold'>Estatuto do RUBY-SR</h2><br>
			<ol>
				<li class='bold'>O grupo de usuários de Ruby de São Roque (RUBY-SR) tem como objetivos:</li>
					<ul>
						<li>Divulgar e promover a linguagem de programação Ruby na cidade de São Roque e imediações (Araçariguama, Mairinque e Sorocaba) através de eventos como palestras, discussões, apresentações de projetos e afins.</li>
						<li>Reuniões presenciais entre os membros do grupo para que estes possam discutir, ensinar e aprender sobre a linguagem Ruby e aspectos relacionados a programação e desenvolvimento de software.</li>
						<li>Colaborar com a comunidade Ruby nacional com a criação e tradução de conteúdos em língua portuguesa.</li>
						<li>Colaborar com a comunidade Ruby global com a criação e manutenção de projetos de código fonte aberto.</li>
					</ul>
				<li class='bold'>Composição do grupo:</li>
					<ul>
						<li>Podem participar do grupo todos aqueles que desejarem, sendo vetada a discriminação dentro do mesmo, seja racial, cultural, religiosa ou sexual de acordo com a constituição brasileira.</li>
						<li>O grupo é composto por pessoas que estejam interessadas em ensinar, aprender e evoluir no aprendizado da linguagem Ruby e do desenvolvimento de software em geral.</li>
					</ul>
			</ol>
			</div>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<% provide :title, 'Home' %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class='col-md-8 col-md-offset-2'>
			<h2 class='bold'>RUBY-SR</h2><br>
			<p>Somos um grupo de pessoas interessadas em aprender, ensinar e divulgar o uso da linguagem de programação Ruby, seu ecossistema e outros assuntos e tecnologias relacionados ao desenvolvimento de software. Pretendemos realizar alguns encontros presenciais durante o ano com o objetivo de compartilhar conhecimento, conhecer pessoas novas e rever o(a)s amigo(a)s.</p>
			<br>

			<h2 class='bold'>Como participar do RUBY-SR</h2>
			<p>Para saber dos encontros presenicais acompanhe nossa página no <%= link_to 'Meetup', '', 'data-toggle': "modal", 'data-target': "#myModal"%>. Para divulgação de vagas, projetos e dúvidas em geral há clássica <%= link_to 'lista de discussão', '', 'data-toggle': "modal", 'data-target': "#myModal" %>, o <%= link_to 'grupo do Facebook', 'https://www.facebook.com/groups/311591792851775/' %>, e finalmente o <%= link_to 'grupo do Telegram', '', 'data-toggle': "modal", 'data-target': "#myModal" %>.</p>
			</div>
			<br>

			<div class='col-md-8 col-md-offset-2' id='members'>
				<h3 class='text-center'>Lista de membros</h3>
				<p class='text-center'>Inscreva-se na nossa lista de membros
				e fique por <br>dentro de tudo o que acontece.</p>
				<br>

				<%= render 'members/form', member: @member %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
				<div class="col-md-4">
					<h3 class='bold'>RubySR</h3>
					<%= link_to 'contato@rubysr.com.br', '' %>
				</div>
				<div class="col-md-4">
					<ul class="list-unstyled">
						<li>
							<i class="fab fa-github"></i>
							<%= link_to 'ruby-sr', '', 'data-toggle': "modal", 'data-target': "#myModal" %>
						</li>
						<li>
							<i class="fab fa-twitter"></i>
							<%= link_to 'ruby_sr', '#', 'data-toggle': "modal", 'data-target': "#myModal" %>
						</li>
						<li>
							<i class="fab fa-youtube"></i>
							<%= link_to 'RubySRtalks', '#', 'data-toggle': "modal", 'data-target': "#myModal" %>
						</li>
						<li>
							<i class="fab fa-facebook"></i>
							<%= link_to 'Grupo no Facebook', 'https://www.facebook.com/groups/311591792851775/' %>
						</li>
						<li>
							<i class="fab fa-google-plus"></i>
							<%= link_to 'Lista de discussão', '', 'data-toggle': "modal", 'data-target': "#myModal" %>
						</li>
					</ul>
				</div>
				<div class="col-md-4">
					<p>Somos o grupo de usuários Ruby de <span class='bold'>São Roque</span></p>
					<small><%= Date.today.year %> &copy - Todos os direitos reservados.</small>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
				<i class="far fa-gem"></i> RUBY-SR
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Inicio', root_path %></li>
        <li><%= link_to 'Sobre',  about_index_path %></li>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Dashboard', rails_admin_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>RubySR - <%= yield :title %></title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css"><%= yield :css %></style>
    <script type="text/javascript"><%= yield :js %></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= alertify_flash(wait: 5) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  </head>
  <body class='<%= controller.controller_name %>' data-spy='scroll'>
    <%= render partial: 'shared/under-construct' %>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
	<div class="field col-md-4 col-sm-12">
		<div class='input-group'>
			<div class='input-group-addon'><i class="far fa-user-circle"></i></div>
			<%= f.text_field :name, class: 'form-control', required: 'required',
			placeholder: 'Digite o nome', autocomplete: 'off' %>
		</div>
	</div>
	<div class="field col-md-4 col-sm-12">
		<div class='input-group'>
			<div class='input-group-addon'><i class="fas fa-at"></i>	</div>
			<%= f.email_field :email, class: 'form-control', required: 'required',
			placeholder: 'Digite o e-mail', autocomplete: 'off' %>
		</div>
	</div>
	<div class="field col-md-4 col-sm-12">
		<%= f.submit 'Inscreva-me', class: 'btn btn-danger btn-lg top' %>
	</div>
<% end %>

app/views/shared/_under-construct.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="bold modal-title" id="myModalLabel">
        <span style='color: #b80000;'>RubySR</span> </h4>
      </div>
      <div class="modal-body text-center">
        <i class="far fa-gem" style='font-size: 43px; color: #b80000;'></i>
        <h4 class='bold'>Em Construção</h4>
        <blockquote>Estamos trabalhando ná construção da comunidade
        perfeita pra você, enquanto isso cadastre-se em nossa lista de membros
        e quandos lançarmos nossa plataforma definitia, lhe avisaremos</blockquote>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>